import React,{useEffect,useState} from 'react';
import {useNavigate,useParams} from 'react-router-dom';
import {Loader2} from 'lucide-react';
import {contentPlanService} from './contentPlanService';
import {buildHistorySummary,generateWeeklyReport} from './plannerV3AiService';
import type {ContentPlan,PostMetrics,TaskStatus,WeeklyReport} from './plannerV3Types';
import MetricsCapture from './components/MetricsCapture';
import WeeklyReportView from './components/WeeklyReportView';
export default function PlannerV3Closing(){const{id=''}=useParams();const nav=useNavigate();const[plan,setPlan]=useState<ContentPlan|null>(null);const[closing,setClosing]=useState(false);const[error,setError]=useState('');useEffect(()=>{void contentPlanService.getPlan(id).then(setPlan)},[id]);if(!plan)return <div className="flex min-h-[50vh] items-center justify-center"><Loader2 className="animate-spin"/></div>;const update=async(taskId:string,status:TaskStatus)=>{await contentPlanService.updateTaskStatus(id,taskId,status);setPlan(p=>p?({...p,tasks:p.tasks.map(t=>t.id===taskId?{...t,status}:t)}):p)};const save=async(taskId:string,m:PostMetrics)=>{await contentPlanService.saveTaskMetrics(id,taskId,m);setPlan(p=>p?({...p,tasks:p.tasks.map(t=>t.id===taskId?{...t,metrics:m}:t)}):p)};const close=async()=>{setClosing(true);setError('');try{const report=await generateWeeklyReport(plan);const withReport={...plan,weeklyReport:report};const history=buildHistorySummary(withReport);await contentPlanService.closePlan(id,report,history);setPlan({...withReport,status:'closed',historySummary:history});}catch{setError('No pudimos crear tu informe. Inténtalo nuevamente.');}finally{setClosing(false)}};const next=()=>nav('/planner/nuevo',{state:{brandId:plan.brandId,focus:plan.monthlyFocus,previousPlanId:plan.id,skipToRhythm:true}});
  if(plan.weeklyReport)return <main className="mx-auto max-w-3xl px-4 py-8"><WeeklyReportView report={plan.weeklyReport} plan={plan} onNext={next}/></main>;const done=plan.tasks.filter(t=>t.status==='done');return <main className="mx-auto max-w-3xl space-y-7 px-4 py-8"><header><p className="text-xs font-black uppercase text-[#F72C5B]">Cierre de semana</p><h1 className="mt-1 text-3xl font-black">Veamos qué funcionó</h1></header><section><h2 className="text-xl font-black">1. ¿Qué publicaste?</h2><p className="text-sm text-slate-500">Marca lo que realmente publicaste — sin culpa, esto es para aprender.</p><div className="mt-3 space-y-2">{plan.tasks.map(t=><div key={t.id} className="flex items-center justify-between rounded-2xl border bg-white p-3"><span className="pr-3 text-sm font-bold">{t.title}</span><select value={t.status} onChange={e=>void update(t.id,e.target.value as TaskStatus)} className="rounded-xl border p-2 text-xs"><option value="pending">Pendiente</option><option value="done">Publicado</option><option value="skipped">No publicado</option></select></div>)}</div></section><section><h2 className="text-xl font-black">2. Registra tus resultados</h2><p className="text-sm text-slate-500">En Instagram: abre tu publicación → Ver estadísticas → captura de pantalla. Es opcional.</p><p className="mt-2 text-xs font-black text-[#F72C5B]">{done.filter(t=>t.metrics).length} de {done.length} con resultados</p><div className="mt-3 space-y-3">{done.map(t=><MetricsCapture key={t.id} task={t} onSave={m=>save(t.id,m)}/>)}</div></section><section className="rounded-3xl bg-slate-950 p-5 text-white"><h2 className="text-xl font-black">3. Recibe tu informe</h2><p className="mt-1 text-sm text-slate-300">Usaremos lo que registraste para mejorar tu próxima semana.</p>{error&&<p className="mt-3 text-sm text-rose-300">{error}</p>}<button disabled={closing} onClick={()=>void close()} className="mt-4 flex w-full items-center justify-center gap-2 rounded-2xl bg-[#F72C5B] p-4 font-black disabled:opacity-50">{closing&&<Loader2 className="animate-spin" size={18}/>} {closing?'Analizando tu semana…':'Cerrar semana y ver mi informe'}</button></section></main>;
}
