import React, { useEffect, useState } from 'react';
import { useLocation, useNavigate } from 'react-router-dom';
import { Loader2 } from 'lucide-react';
import { auth } from '../../../firebase';
import { brandProfileService } from '../../../services/brandProfileService';
import type { BrandProfile } from '../../brandProfiles/types';
import { contentPlanService } from './contentPlanService';
import { generateWeeklyPlan } from './plannerV3AiService';
import { GOAL_LABELS, type MonthlyFocus, type PlanGoal, type PlanPlatform } from './plannerV3Types';

const platforms: PlanPlatform[]=['Instagram Feed','Instagram Stories','TikTok','Facebook','WhatsApp Estados'];
export default function PlannerV3Wizard(){
  const nav=useNavigate(); const location=useLocation(); const seed=(location.state||{}) as {brandId?:string;focus?:MonthlyFocus;previousPlanId?:string;skipToRhythm?:boolean};
  const [brands,setBrands]=useState<BrandProfile[]>([]); const [loading,setLoading]=useState(true); const [step,setStep]=useState(seed.skipToRhythm?3:1); const [brandId,setBrandId]=useState(seed.brandId||'');
  const [focus,setFocus]=useState<MonthlyFocus>(seed.focus||{goal:'sell',focusProduct:'',notes:''}); const [frequency,setFrequency]=useState<3|5|7>(5); const [selected,setSelected]=useState<PlanPlatform[]>(['Instagram Feed','Instagram Stories']); const [generating,setGenerating]=useState(false); const [error,setError]=useState('');
  useEffect(()=>{ const uid=auth.currentUser?.uid; if(!uid){setLoading(false);return;} brandProfileService.getBrandProfiles(uid).then(x=>{setBrands(x);if(!brandId)setBrandId((x.find(b=>b.isDefault)||x[0])?.id||'');}).finally(()=>setLoading(false));},[]);
  const create=async()=>{const brand=brands.find(b=>b.id===brandId);if(!brand||!selected.length)return;setGenerating(true);setError('');try{const plans=await contentPlanService.listPlans();const active=plans.find(p=>p.brandId===brand.id&&p.status==='active');if(active&&active.id!==seed.previousPlanId&&confirm('Tienes una semana activa con esta marca. Pulsa Aceptar para revisarla primero, o Cancelar para crear una nueva.')){nav(`/planner/${active.id}/cierre`);return;}const history=await contentPlanService.getHistoryForBrand(brand.id);const weekNumber=(history.at(-1)?.weekNumber||0)+1;const generated=await generateWeeklyPlan({brand,focus,frequency,platforms:selected,weekNumber,history});/* TODO Nico: decidir si el plan consume créditos */const id=await contentPlanService.createPlan({brandId:brand.id,brandName:brand.brandName,monthlyFocus:focus,weekNumber,frequency,platforms:selected,status:'active',...generated,previousPlanId:seed.previousPlanId});nav(`/planner/${id}`);}catch{setError('No pudimos preparar tu semana. Inténtalo de nuevo.');}finally{setGenerating(false);}};
  if(loading)return <div className="flex min-h-[50vh] items-center justify-center"><Loader2 className="animate-spin"/></div>;
  if(!brands.length)return <main className="mx-auto max-w-xl px-4 py-12 text-center"><h1 className="text-3xl font-black">Primero creemos tu marca</h1><p className="mt-3 text-slate-600">Usaremos la información de tu marca para darte ideas hechas a tu medida. Solo toma unos pocos pasos.</p><button onClick={()=>nav('/mis-marcas')} className="mt-6 rounded-2xl bg-[#F72C5B] px-6 py-4 font-black text-white">Crear mi perfil de marca</button></main>;
  return <main className="mx-auto max-w-2xl px-4 py-8"><div className="mb-8"><div className="h-2 rounded-full bg-slate-100"><div className="h-full rounded-full bg-[#F72C5B] transition-all" style={{width:`${step/3*100}%`}}/></div><p className="mt-2 text-xs font-black uppercase text-slate-400">Paso {step} de 3</p></div>
    {step===1&&<section><h1 className="text-3xl font-black">¿Con qué marca trabajamos?</h1><div className="mt-5 space-y-3">{brands.map(b=><button key={b.id} onClick={()=>setBrandId(b.id)} className={`w-full rounded-2xl border-2 p-4 text-left ${brandId===b.id?'border-[#F72C5B] bg-rose-50':'border-slate-200 bg-white'}`}><b>{b.brandName}</b><p className="text-sm text-slate-500">{b.mainCategory} · {b.completionScore}% completo</p>{brandId===b.id&&b.completionScore<40&&<p className="mt-2 text-xs text-amber-700">Tu plan saldrá mejor si completas tu marca, pero puedes seguir igual.</p>}</button>)}</div><button onClick={()=>setStep(2)} className="mt-6 w-full rounded-2xl bg-slate-900 p-4 font-black text-white">Continuar</button></section>}
    {step===2&&<section><h1 className="text-3xl font-black">¿Qué quieres lograr este mes?</h1><div className="mt-5 grid grid-cols-2 gap-3">{(Object.keys(GOAL_LABELS) as PlanGoal[]).map(g=><button key={g} onClick={()=>setFocus(f=>({...f,goal:g}))} className={`rounded-2xl border-2 p-4 font-black ${focus.goal===g?'border-[#F72C5B] bg-rose-50':'border-slate-200'}`}>{GOAL_LABELS[g]}</button>)}</div><input value={focus.focusProduct} onChange={e=>setFocus(f=>({...f,focusProduct:e.target.value}))} placeholder="Producto o servicio que quieres destacar (opcional)" className="mt-4 w-full rounded-2xl border p-4"/><textarea value={focus.notes} onChange={e=>setFocus(f=>({...f,notes:e.target.value}))} placeholder="Algo que debamos saber, ej.: tengo liquidación el viernes" className="mt-3 w-full rounded-2xl border p-4"/><div className="mt-5 flex gap-2"><button onClick={()=>setStep(1)} className="px-4">Atrás</button><button onClick={()=>setStep(3)} className="flex-1 rounded-2xl bg-slate-900 p-4 font-black text-white">Continuar</button></div></section>}
    {step===3&&<section><h1 className="text-3xl font-black">Elige tu ritmo y tus redes</h1><div className="mt-5 grid grid-cols-3 gap-3">{([3,5,7] as const).map(n=><button key={n} onClick={()=>setFrequency(n)} className={`rounded-2xl border-2 p-4 ${frequency===n?'border-[#F72C5B] bg-rose-50':'border-slate-200'}`}><b>{n}</b><span className="block text-xs">por semana</span>{n===5&&<span className="mt-1 block text-[9px] font-bold text-[#F72C5B]">RECOMENDADO</span>}</button>)}</div><div className="mt-5 space-y-2">{platforms.map(p=><label key={p} className="flex items-center gap-3 rounded-xl border p-3"><input type="checkbox" checked={selected.includes(p)} onChange={()=>setSelected(x=>x.includes(p)?x.filter(v=>v!==p):[...x,p])}/><span className="font-bold">{p}</span></label>)}</div>{error&&<p className="mt-4 text-center text-sm text-red-600">{error}</p>}<div className="mt-5 flex gap-2"><button onClick={()=>setStep(2)} className="px-4">Atrás</button><button disabled={generating||!selected.length} onClick={()=>void create()} className="flex flex-1 items-center justify-center gap-2 rounded-2xl bg-[#F72C5B] p-4 font-black text-white disabled:opacity-50">{generating?<><Loader2 className="animate-spin" size={18}/> Preparando tu semana…</>:'Preparar mi semana ✨'}</button></div></section>}
  </main>;
}
