import React,{useEffect,useState} from 'react';
import {useNavigate,useParams} from 'react-router-dom';
import {ChevronDown,Loader2} from 'lucide-react';
import {contentPlanService} from './contentPlanService';
import {MODULE_ROUTES} from './moduleCatalog';
import {GOAL_LABELS,type ContentPlan,type TaskStatus} from './plannerV3Types';
import TaskCard from './components/TaskCard';
export default function PlannerV3Week(){const {id=''}=useParams();const nav=useNavigate();const [plan,setPlan]=useState<ContentPlan|null>(null);const [strategyOpen,setStrategyOpen]=useState(true);const load=()=>contentPlanService.getPlan(id).then(setPlan);useEffect(()=>{void load();const h=(e:Event)=>{const d=(e as CustomEvent).detail;if(d.projectId===id)void load();};window.addEventListener('planner:task:complete',h);return()=>window.removeEventListener('planner:task:complete',h);},[id]);
  if(!plan)return <div className="flex min-h-[50vh] items-center justify-center"><Loader2 className="animate-spin"/></div>;const done=plan.tasks.filter(t=>t.status==='done').length;const status=async(taskId:string,s:TaskStatus)=>{await contentPlanService.updateTaskStatus(id,taskId,s);setPlan(p=>p?({...p,tasks:p.tasks.map(t=>t.id===taskId?{...t,status:s}:t)}):p);};
  const create=(task:typeof plan.tasks[number])=>{window.dispatchEvent(new CustomEvent('planner:task:activate',{detail:{...task,module:task.toolModule,projectId:id}}));const route=MODULE_ROUTES[task.toolModule];if(route)nav(task.toolModule==='prompt'?`${route}?prompt=${encodeURIComponent(task.prompt)}`:route);};
  return <main className="mx-auto max-w-4xl space-y-5 px-4 py-7"><button onClick={()=>nav('/planner')} className="text-sm font-bold text-slate-500">← Mis planes</button><header><p className="text-xs font-black uppercase tracking-widest text-[#F72C5B]">{plan.brandName}</p><h1 className="text-3xl font-black">Semana {plan.weekNumber}</h1><p className="text-slate-500">{GOAL_LABELS[plan.monthlyFocus.goal]}</p><div className="mt-4 h-2 rounded-full bg-slate-100"><div className="h-full rounded-full bg-[#F72C5B]" style={{width:`${done/Math.max(1,plan.tasks.length)*100}%`}}/></div></header><section className="rounded-3xl bg-slate-950 p-5 text-white"><button onClick={()=>setStrategyOpen(v=>!v)} className="flex w-full items-center justify-between text-left font-black">¿Por qué este plan funciona?<ChevronDown className={strategyOpen?'rotate-180':''}/></button>{strategyOpen&&<p className="mt-3 leading-relaxed text-slate-300">{plan.strategySummary}</p>}</section><div className="space-y-4">{[...plan.tasks].sort((a,b)=>a.date.localeCompare(b.date)).map(t=><TaskCard key={t.id} task={t} onStatus={s=>void status(t.id,s)} onCreate={()=>create(t)}/>)}</div><button onClick={()=>nav(`/planner/${id}/cierre`)} className="w-full rounded-2xl border-2 border-[#F72C5B] p-4 font-black text-[#F72C5B]">Cerrar semana y ver resultados</button></main>;
}
