import React, { useState } from 'react';
import { Loader2, Sparkles, Upload } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { ref, uploadBytes, getDownloadURL } from 'firebase/storage';
import { storage } from '../../firebase';
import { analyzeLogoForBrand, extractBrandFromInterview, type InterviewExtraction, type LogoAnalysis } from '../../services/brandIntelligenceService';
import { brandProfileService } from '../../services/brandProfileService';
import { BrandAISummaryStep } from './components/BrandAISummaryStep';
import { BrandCard2 } from './components/BrandCard2';
import { InterviewReview } from './components/InterviewReview';
import { LogoIntelPanel } from './components/LogoIntelPanel';
import { EMPTY_BRAND_PROFILE, type BrandProfile } from './types';

const tones=['Cercana','Elegante','Juvenil','Divertida','Premium','Directa','Profesional','Inspiradora'];
const categories=['Moda','Belleza','Comida','Hogar y decoración','Servicios','Artesanía'];
const ages=['18–24','25–34','35–44','45–54','55+'];
export function BrandCoreWizard({ userId, onDone, onBack }: { userId:string; onDone:(p:BrandProfile)=>Promise<void>; onBack:()=>void }) {
  const nav=useNavigate();const [step,setStep]=useState(1);const [id,setId]=useState('');const [data,setData]=useState<Partial<BrandProfile>>({...EMPTY_BRAND_PROFILE,userId,brandName:''});const [interview,setInterview]=useState('');const [extraction,setExtraction]=useState<InterviewExtraction|null>(null);const [logo,setLogo]=useState<LogoAnalysis|null>(null);const [busy,setBusy]=useState('');const [error,setError]=useState('');const [done,setDone]=useState(false);
  const merge=(patch:Partial<BrandProfile>)=>setData(d=>({...d,...patch}));
  const save=async()=>{if(id){await brandProfileService.updateBrandProfile(userId,id,data);return id;}const newId=await brandProfileService.createBrandProfile(userId,data as BrandProfile);setId(newId);return newId;};
  const analyzeLogo=async(file?:File)=>{if(!file)return;setBusy('logo');setError('');try{const result=await analyzeLogoForBrand(await new Promise<string>((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result).split(',')[1]);r.onerror=reject;r.readAsDataURL(file)}),file.type,data.brandName||'',data.mainCategory||'');const brandId=await save();const path=`users/${userId}/brandProfiles/${brandId}/logos/${Date.now()}_${file.name.replace(/[^a-zA-Z0-9._-]/g,'_')}`;const storageRef=ref(storage,path);await uploadBytes(storageRef,file);const url=await getDownloadURL(storageRef);merge({visualIdentity:{...data.visualIdentity!,assets:[...(data.visualIdentity?.assets||[]).filter(a=>a.type!=='logo'),{id:String(Date.now()),type:'logo',name:file.name,url,path,fileName:file.name,mimeType:file.type,uploadedAt:Date.now()}]}});setLogo(result);}catch(e){setError(e instanceof Error&&e.message==='NOT_A_LOGO'?'Esa imagen no parece un logo. Sube tu logo o salta este paso.':'No pude leer tu logo. Puedes continuar sin él.');}finally{setBusy('');}};
  const next=async()=>{setBusy('save');try{await save();setStep(s=>Math.min(4,s+1));}finally{setBusy('');}};
  const finish=async()=>{setBusy('save');const brandId=await save();const saved=await brandProfileService.getBrandProfile(userId,brandId);if(saved){setData(saved);setDone(true);await onDone(saved);}setBusy('');};
  if(done)return <main className="mx-auto max-w-2xl px-4 py-10 text-center"><Sparkles className="mx-auto text-[#F72C5B]"/><h1 className="mt-4 text-3xl font-bold">Tu marca ya tiene cerebro propio</h1><p className="mt-2 text-sm text-slate-600">Puedes seguir mejorándola cuando quieras o crear tu primera semana.</p><div className="mt-6 grid gap-3 sm:grid-cols-3"><button onClick={()=>nav('/planner/nuevo',{state:{brandId:id}})} className="min-h-11 rounded-[14px] bg-[#F72C5B] px-4 font-bold text-white">Crear mi primer plan</button><button onClick={()=>{setDone(false);setStep(1);setId('');setData({...EMPTY_BRAND_PROFILE,userId,brandName:''})}} className="min-h-11 rounded-[14px] border px-4 font-bold">Crear otra marca</button><button onClick={onBack} className="min-h-11 rounded-[14px] border px-4 font-bold">Ver mis marcas</button></div></main>;
  return <main className="mx-auto max-w-5xl px-4 py-6"><div className="sticky top-0 z-20 bg-slate-50/95 py-3 backdrop-blur sm:hidden"><BrandCard2 profile={data} compact/></div><div className="mb-7"><p className="text-[11px] font-bold uppercase tracking-[.08em] text-[#F72C5B]">Paso {step} de 4</p><div className="mt-2 h-1 rounded bg-slate-200"><div className="h-full rounded bg-[#F72C5B]" style={{width:`${step*25}%`}}/></div></div><div className="grid gap-8 lg:grid-cols-[1fr_320px]"><div className="rounded-2xl bg-white p-5 shadow-sm">
    {step===1&&<div className="space-y-5"><div><h1 className="text-2xl font-bold text-slate-800">Tu marca</h1><p className="mt-1 text-sm text-slate-600">Empecemos por lo esencial.</p></div><label className="block text-[13px] font-semibold">Nombre de tu marca<input value={data.brandName||''} onChange={e=>merge({brandName:e.target.value})} className="mt-1 min-h-11 w-full rounded-xl border px-3 text-sm font-normal"/></label><label className="block text-[13px] font-semibold">Categoría<select value={data.mainCategory||''} onChange={e=>merge({mainCategory:e.target.value})} className="mt-1 min-h-11 w-full rounded-xl border px-3 font-normal"><option value="">Elige una</option>{categories.map(x=><option key={x}>{x}</option>)}<option>Otro</option></select></label>{data.mainCategory==='Otro'&&<input aria-label="Escribe tu categoría" placeholder="Escribe tu categoría" onChange={e=>merge({mainCategory:e.target.value})} className="min-h-11 w-full rounded-xl border px-3"/>}<label className="flex min-h-28 cursor-pointer flex-col items-center justify-center rounded-2xl border-2 border-dashed p-5 text-sm font-semibold"><Upload/><span className="mt-2">{busy==='logo'?'Leyendo tu logo…':'Sube tu logo (opcional)'}</span><input type="file" accept="image/*" className="hidden" disabled={!data.brandName||!!busy} onChange={e=>void analyzeLogo(e.target.files?.[0])}/></label>{error&&<p className="text-sm text-rose-600">{error}</p>}{logo&&<LogoIntelPanel analysis={logo} onAccept={()=>{merge({visualIdentity:{...data.visualIdentity!,colors:logo.colors,visualStyle:logo.suggestedStyles,contentMood:logo.suggestedMoods}});setLogo(null)}} onDiscard={()=>setLogo(null)}/>}</div>}
    {step===2&&<div className="space-y-5"><div><h1 className="text-2xl font-bold">Cuéntale tu marca a Luz</h1><p className="mt-1 text-sm text-slate-600">Qué vendes, a quién y por qué elegirte. Escribe como se lo contarías a una amiga.</p></div>{!extraction?<><textarea value={interview} onChange={e=>setInterview(e.target.value)} placeholder="Creo accesorios hechos a mano para mujeres que quieren sentirse únicas…" className="min-h-40 w-full rounded-xl border p-4 text-sm"/><button disabled={interview.trim().length<30||!!busy} onClick={async()=>{setBusy('interview');setError('');try{setExtraction(await extractBrandFromInterview(interview,data.brandName||''))}catch{setError('No pude ordenar tu texto esta vez. Intenta de nuevo o continúa y completa después.')}finally{setBusy('')}}} className="min-h-11 w-full rounded-[14px] bg-[#F72C5B] font-bold text-white disabled:opacity-50">{busy==='interview'?'Ordenando tu marca…':'Ordenar mi marca ✦'}</button>{interview.length<30&&<p className="text-xs text-slate-500">Cuéntame un poco más — con 2 o 3 frases alcanza.</p>}</>:<><InterviewReview value={extraction} onChange={setExtraction}/><button onClick={()=>{merge({shortDescription:extraction.shortDescription,targetCustomer:{...data.targetCustomer!,freeDescription:extraction.customerFreeDescription,buyingMotivation:extraction.buyingMotivation},positioning:{...data.positioning!,mainDifferentiatorText:extraction.mainDifferentiatorText,brandPromise:extraction.brandPromise},voice:{...data.voice!,toneKeywords:extraction.suggestedTones}});setStep(3)}} className="min-h-11 w-full rounded-[14px] bg-[#F72C5B] font-bold text-white">Así es mi marca →</button></>}</div>}
    {step===3&&<div className="space-y-5"><div><h1 className="text-2xl font-bold">Tu clienta y tu voz</h1><p className="mt-1 text-sm text-slate-600">Ajusta cómo quieres sonar y a quién quieres llegar.</p></div><label className="block text-[13px] font-semibold">Tu clienta ideal<textarea value={data.targetCustomer?.freeDescription||''} onChange={e=>merge({targetCustomer:{...data.targetCustomer!,freeDescription:e.target.value}})} className="mt-1 min-h-24 w-full rounded-xl border p-3 font-normal"/></label><div><p className="text-[13px] font-semibold">Edad aproximada</p><div className="mt-2 grid grid-cols-2 gap-2 sm:grid-cols-5">{ages.map(age=>{const selected=(data.targetCustomer?.ageRange||'').split(',').map(x=>x.trim()).filter(Boolean);return <button key={age} type="button" onClick={()=>{const next=selected.includes(age)?selected.filter(x=>x!==age):[...selected,age];merge({targetCustomer:{...data.targetCustomer!,ageRange:next.join(', ')}})}} className={`min-h-11 rounded-xl border px-3 text-[13px] font-semibold ${selected.includes(age)?'border-[#F72C5B] bg-rose-50 text-[#F72C5B]':''}`}>{age}</button>})}</div></div><div><p className="text-[13px] font-semibold">Tu tono</p><div className="mt-2 grid grid-cols-2 gap-2 sm:grid-cols-4">{tones.map(t=><button key={t} onClick={()=>merge({voice:{...data.voice!,toneKeywords:data.voice?.toneKeywords.includes(t)?data.voice.toneKeywords.filter(x=>x!==t):[...(data.voice?.toneKeywords||[]),t]}})} className={`min-h-11 rounded-xl border px-3 text-[13px] font-semibold ${data.voice?.toneKeywords.includes(t)?'border-[#F72C5B] bg-rose-50 text-[#F72C5B]':''}`}>{t}</button>)}</div></div><label className="block text-[13px] font-semibold">Palabras que nunca usarías<input value={data.voice?.forbiddenWords?.join(', ')||''} onChange={e=>merge({voice:{...data.voice!,forbiddenWords:e.target.value.split(',').map(x=>x.trim()).filter(Boolean)}})} className="mt-1 min-h-11 w-full rounded-xl border px-3 font-normal"/></label></div>}
    {step===4&&<div className="space-y-5"><div><h1 className="text-2xl font-bold">La esencia de tu marca</h1><p className="mt-1 text-sm text-slate-600">Luz convertirá todo lo que contaste en una guía que usarán el Planner y los estudios creativos.</p></div><BrandAISummaryStep data={data} onChange={aiSummary=>merge({aiSummary})}/></div>}
    <div className="mt-8 flex gap-3 border-t pt-5"><button onClick={()=>step===1?onBack():setStep(s=>s-1)} className="min-h-11 px-4 font-semibold text-slate-600">Atrás</button>{step<4&&step!==2&&<button disabled={!data.brandName||!!busy} onClick={()=>void next()} className="min-h-11 flex-1 rounded-[14px] bg-[#F72C5B] px-4 font-bold text-white disabled:opacity-50">{busy==='save'?<Loader2 className="mx-auto animate-spin"/>:'Continuar'}</button>}{step===4&&<button onClick={()=>void finish()} disabled={!!busy} className="min-h-11 flex-1 rounded-[14px] bg-[#F72C5B] px-4 font-bold text-white">Guardar y terminar</button>}</div>
    </div><div className="hidden lg:block"><div className="sticky top-6"><BrandCard2 profile={data}/></div></div></div></main>;
}
