import React,{useState} from 'react';
import {BarChart3,BriefcaseBusiness,MessageCircle,Palette,RefreshCw,Target} from 'lucide-react';
import {brandProfileService} from '../../services/brandProfileService';
import {BrandAISummaryStep} from './components/BrandAISummaryStep';
import {AreaSheet} from './components/AreaSheet';
import {BrandCard2} from './components/BrandCard2';
import {SocialInsightsArea} from './components/SocialInsightsArea';
import type {BrandProfile} from './types';
type Area='positioning'|'sales'|'visual'|'social'|'words'|'summary';
export function BrandLivingProfile({userId,profile,onBack,onUpdated}:{userId:string;profile:BrandProfile;onBack:()=>void;onUpdated:(p:BrandProfile)=>Promise<void>}){const[data,setData]=useState(profile);const[area,setArea]=useState<Area|null>(null);const save=async(patch:Partial<BrandProfile>)=>{const next={...data,...patch};await brandProfileService.updateBrandProfile(userId,data.id,next);const fresh=await brandProfileService.getBrandProfile(userId,data.id);if(fresh){setData(fresh);await onUpdated(fresh)}};const areas=[{id:'positioning' as Area,icon:Target,title:'Posicionamiento',desc:'Aclara por qué elegirte a ti.',reward:'+10% de precisión'},{id:'sales' as Area,icon:BriefcaseBusiness,title:'Cómo vendes',desc:'Mejora llamados a la acción.',reward:'+15% comercial'},{id:'visual' as Area,icon:Palette,title:'Estilo visual pro',desc:'Imágenes más coherentes.',reward:'+10% visual'},{id:'social' as Area,icon:BarChart3,title:'Tus redes',desc:'El Planner usa datos reales.',reward:'Horarios reales'},{id:'words' as Area,icon:MessageCircle,title:'Clienta y palabras',desc:'Ajusta edades y la voz de tus captions.',reward:'Mejor voz'},{id:'summary' as Area,icon:RefreshCw,title:'Resumen IA',desc:'Regenera tu guía maestra.',reward:'Todo sincronizado'}];
return <main className="mx-auto max-w-5xl space-y-7 px-4 py-7"><button onClick={onBack} className="min-h-11 text-sm font-semibold text-slate-600">← Mis marcas</button><BrandCard2 profile={data}/><div><h1 className="text-2xl font-bold text-slate-800">Haz crecer el cerebro de tu marca</h1><p className="mt-1 text-sm text-slate-600">Completa solo el área que necesites. Cada dato mejora una parte visible de Luz.</p></div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{areas.map(a=><button key={a.id} onClick={()=>setArea(a.id)} className="min-h-36 rounded-2xl border border-slate-200 bg-white p-5 text-left shadow-sm transition hover:-translate-y-0.5 hover:border-[#F72C5B]"><a.icon className="text-[#F72C5B]"/><h2 className="mt-3 text-lg font-bold">{a.title}</h2><p className="mt-1 text-sm text-slate-600">{a.desc}</p><p className="mt-2 text-xs font-semibold text-[#F72C5B]">{a.reward}</p></button>)}</div>
{area&&<AreaSheet title={areas.find(a=>a.id===area)?.title||''} onClose={()=>setArea(null)}>{area==='social'?<SocialInsightsArea current={data.socialInsights} onSave={async v=>{await brandProfileService.updateBrandSocialInsights(userId,data.id,v);const fresh=await brandProfileService.getBrandProfile(userId,data.id);if(fresh)setData(fresh)}}/>:area==='summary'?<><BrandAISummaryStep data={data} onChange={aiSummary=>setData(d=>({...d,aiSummary}))}/><button onClick={()=>void save({aiSummary:data.aiSummary})} className="mt-5 min-h-11 w-full rounded-[14px] bg-[#F72C5B] font-bold text-white">Guardar resumen</button></>:<SimpleArea area={area} data={data} onSave={save}/>}</AreaSheet>}</main>}
function SimpleArea({area,data,onSave}:{area:Area;data:BrandProfile;onSave:(p:Partial<BrandProfile>)=>Promise<void>}) {
  const [draft,setDraft]=useState(data);
  const ageOptions=['18–24','25–34','35–44','45–54','55+'];
  const selectedAges=draft.targetCustomer.ageRange.split(',').map(x=>x.trim()).filter(Boolean);
  return <div className="space-y-4">
    {area==='positioning'&&<><Field label="Tu diferencial" value={draft.positioning.mainDifferentiatorText} onChange={v=>setDraft({...draft,positioning:{...draft.positioning,mainDifferentiatorText:v}})}/><Field label="Tu promesa" value={draft.positioning.brandPromise} onChange={v=>setDraft({...draft,positioning:{...draft.positioning,brandPromise:v}})}/></>}
    {area==='sales'&&<><Field label="Canales de venta (separados por coma)" value={draft.commercialRules.mainSalesChannels.join(', ')} onChange={v=>setDraft({...draft,commercialRules:{...draft.commercialRules,mainSalesChannels:v.split(',').map(x=>x.trim()).filter(Boolean)}})}/><Field label="Llamados a la acción" value={draft.commercialRules.preferredCTA.join(', ')} onChange={v=>setDraft({...draft,commercialRules:{...draft.commercialRules,preferredCTA:v.split(',').map(x=>x.trim()).filter(Boolean)}})}/></>}
    {area==='visual'&&<Field label="Estilos visuales" value={draft.visualIdentity.visualStyle.join(', ')} onChange={v=>setDraft({...draft,visualIdentity:{...draft.visualIdentity,visualStyle:v.split(',').map(x=>x.trim()).filter(Boolean)}})}/>}
    {area==='words'&&<><div><p className="text-[13px] font-semibold text-slate-700">Edad aproximada de tu clienta</p><div className="mt-2 grid grid-cols-2 gap-2 sm:grid-cols-5">{ageOptions.map(age=><button key={age} type="button" onClick={()=>{const next=selectedAges.includes(age)?selectedAges.filter(x=>x!==age):[...selectedAges,age];setDraft({...draft,targetCustomer:{...draft.targetCustomer,ageRange:next.join(', ')}})}} className={`min-h-11 rounded-xl border px-3 text-[13px] font-semibold ${selectedAges.includes(age)?'border-[#F72C5B] bg-rose-50 text-[#F72C5B]':'border-slate-200'}`}>{age}</button>)}</div></div><Field label="Palabras preferidas" value={draft.voice.preferredWords.join(', ')} onChange={v=>setDraft({...draft,voice:{...draft.voice,preferredWords:v.split(',').map(x=>x.trim()).filter(Boolean)}})}/><Field label="Palabras prohibidas" value={draft.voice.forbiddenWords.join(', ')} onChange={v=>setDraft({...draft,voice:{...draft.voice,forbiddenWords:v.split(',').map(x=>x.trim()).filter(Boolean)}})}/></>}
    <button onClick={()=>void onSave(draft)} className="min-h-11 w-full rounded-[14px] bg-[#F72C5B] font-bold text-white">Guardar cambios</button>
  </div>
}
function Field({label,value,onChange}:{label:string;value:string;onChange:(v:string)=>void}){return <label className="block text-[13px] font-semibold text-slate-700">{label}<textarea value={value} onChange={e=>onChange(e.target.value)} className="mt-1 min-h-24 w-full rounded-xl border p-3 text-sm font-normal"/></label>}
